// src/lib/components/wxcn/ForecastDashboard.svelte
<script lang="ts">
	import WeatherForecast from './WeatherForecast.svelte';
	import TideForecast from './TideForecast.svelte';
	import MoonForecast from './MoonForecast.svelte';
	import type {
		ForecastType,
		IconSet,
		LocationInput,
		TideUnit,
		WeatherUnit
	} from '$lib/data/types.js';

	let {
		type = 'summary',
		size = 'default',
		density = 'comfortable',
		weatherUnit = 'fahrenheit',
		windUnit = 'mph',
		tideUnit = 'ft',
		iconType,
		animatedWeatherBackground = false,
		tideLocation,
		location = {
			label: 'Austin, TX',
			latitude: 30.2672,
			longitude: -97.7431
		}
	}: {
		type?: ForecastType;
		size?: 'sm' | 'default' | 'lg';
		density?: 'compact' | 'comfortable';
		weatherUnit?: WeatherUnit;
		windUnit?: 'mph' | 'km/h' | 'm/s' | 'knots';
		tideUnit?: TideUnit;
		iconType?: IconSet;
		animatedWeatherBackground?: boolean;
		location?: LocationInput;
		tideLocation?: LocationInput;
	} = $props();
</script>

<div class="grid gap-4 lg:grid-cols-3">
	<WeatherForecast
		{type}
		{size}
		{density}
		unit={weatherUnit}
		{windUnit}
		{iconType}
		{location}
		animatedBackground={animatedWeatherBackground}
	/>
	<TideForecast {type} {size} {density} unit={tideUnit} {iconType} location={tideLocation} />
	<MoonForecast {type} {size} {density} {iconType} {location} />
</div>

// packages/react/src/components/wxcn/forecast-dashboard.tsx
import type { IconSet } from '../../icons/forecast-icons';
import type {
	ForecastType,
	LocationInput,
	TideUnit,
	WeatherUnit,
	CurrentWeather
} from '@wxcn/core/types.js';
import { WeatherForecast } from './weather-forecast';
import { TideForecast } from './tide-forecast';
import { MoonForecast } from './moon-forecast';

export type ForecastDashboardProps = {
	iconType?: IconSet;
	timeZone?: string;
	type?: ForecastType;
	size?: 'sm' | 'default' | 'lg';
	density?: 'compact' | 'comfortable';
	weatherUnit?: WeatherUnit;
	windUnit?: 'mph' | 'km/h' | 'm/s' | 'knots';
	tideUnit?: TideUnit;
	animatedWeatherBackground?: boolean;
	showTemperatureTrend?: boolean;
	showHighLow?: boolean;
	currentWeather?: CurrentWeather | null;
	location?: LocationInput;
	tideLocation?: LocationInput;
};

export function ForecastDashboard({
	iconType,
	timeZone,
	type = 'summary',
	size = 'default',
	density = 'comfortable',
	weatherUnit = 'fahrenheit',
	windUnit = 'mph',
	tideUnit = 'ft',
	animatedWeatherBackground = false,
	showTemperatureTrend = false,
	showHighLow = false,
	currentWeather,
	tideLocation,
	location
}: ForecastDashboardProps) {
	return (
		<div className="@container/dashboard w-full">
			<div className="grid items-start gap-4 @min-[38rem]/dashboard:grid-cols-2 @min-[52rem]/dashboard:grid-cols-3">
				<div className="min-w-0 @min-[38rem]/dashboard:col-span-2 @min-[52rem]/dashboard:col-span-1">
					<WeatherForecast
						iconType={iconType}
						timeZone={timeZone}
						type={type}
						size={size}
						density={density}
						unit={weatherUnit}
						windUnit={windUnit}
						location={location}
						animatedBackground={animatedWeatherBackground}
						showTemperatureTrend={showTemperatureTrend}
						showHighLow={showHighLow}
						currentWeather={currentWeather}
					/>
				</div>
				<TideForecast
					iconType={iconType}
					timeZone={timeZone}
					type={type}
					size={size}
					density={density}
					unit={tideUnit}
					location={tideLocation}
				/>
				<MoonForecast
					timeZone={timeZone}
					type={type}
					size={size}
					density={density}
					location={location}
				/>
			</div>
		</div>
	);
}

export default ForecastDashboard;
