// packages/svelte/src/components/wxcn/MoonForecast.svelte
<script lang="ts">
	import { onMount, type Snippet } from 'svelte';
	import MoonDisc from './MoonDisc.svelte';
	import * as Card from '../ui/card/index.js';
	import ForecastScreens from './ForecastScreens.svelte';
	import { forecastDays, type ForecastDay } from '@wxcn/core/forecast-days.js';
	import type {
		ForecastType,
		IconSet,
		LocationInput,
		MoonForecast as MoonData
	} from '@wxcn/core/types.js';
	import { sampleMoon, getMoonForecast, getUpcomingMoonPhases } from '@wxcn/core/moon.js';
	let {
		interactive = false,
		timeZone,
		type = 'summary',
		size = 'default',
		density = 'comfortable',
		class: className = '',
		iconType,
		location = { label: 'Austin, TX', latitude: 30.2672, longitude: -97.7431 },
		forecast = sampleMoon,
		sourceLabel = ''
	}: {
		interactive?: boolean;
		timeZone?: string;
		type?: ForecastType;
		size?: 'sm' | 'default' | 'lg';
		density?: 'compact' | 'comfortable';
		class?: string;
		iconType?: IconSet;
		location?: LocationInput;
		forecast?: MoonData;
		sourceLabel?: string;
	} = $props();
	let visitorTimeZone = $state('UTC');
	onMount(() => {
		visitorTimeZone = Intl.DateTimeFormat().resolvedOptions().timeZone;
	});
	const displayTimeZone = $derived(timeZone ?? location.timeZone ?? visitorTimeZone);
	const date = (v: string) =>
		new Intl.DateTimeFormat('en-US', {
			month: 'short',
			day: 'numeric',
			timeZone: displayTimeZone
		}).format(new Date(v));
	const phases = $derived(getUpcomingMoonPhases(new Date(forecast.date)));
	const days = $derived(
		forecastDays(
			phases.map((value) => ({
				time: Date.parse(value.date),
				label: value.phaseName,
				summary: `${value.illumination}% illuminated`,
				details: ''
			})),
			displayTimeZone
		)
	);
</script>

{#snippet cardView(day: ForecastDay | undefined, action: Snippet<[boolean]>)}
	{@const view = day
		? day.entries[0].time === Date.parse(forecast.date)
			? forecast
			: getMoonForecast(new Date(day.entries[0].time))
		: forecast}
	<Card.Header
		><Card.Title>{day?.label ?? 'Moon phase'}</Card.Title><Card.Description
			>{location.label}</Card.Description
		>{@render action(false)}</Card.Header
	>
	<Card.Content class={density === 'compact' ? 'grid gap-3' : 'grid gap-5'}>
		<div
			class={`flex items-center gap-4 ${size === 'lg' ? 'flex-col rounded-lg bg-muted/20 p-5 text-center' : ''}`}
		>
			<MoonDisc
				phase={view.phase ?? view.age / 29.530588853}
				label={`${view.phaseName}, ${view.illumination}% illuminated`}
				class={size === 'sm'
					? 'size-16 shrink-0'
					: size === 'lg'
						? 'size-36 shrink-0'
						: 'size-24 max-w-[28cqw] shrink-0'}
			/>
			<div>
				<p
					style="font-size:clamp(1rem,6cqw,1.5rem)"
					class={`font-medium tracking-tight ${size === 'sm' ? 'text-lg' : 'text-2xl'}`}
				>
					{view.phaseName}
				</p>
				<p class="mt-2 text-sm text-muted-foreground">{view.illumination}% illuminated</p>
			</div>
		</div>
		{#if type !== 'simple'}<dl class="moon-data divide-y text-sm">
				<div class="flex justify-between gap-4 pb-3">
					<dt class="text-muted-foreground">Moon age</dt>
					<dd>{view.age} days</dd>
				</div>
				<div class="flex justify-between gap-4 py-3">
					<dt class="text-muted-foreground">Next full moon</dt>
					<dd>{date(view.nextFullMoon)}</dd>
				</div>
				<div class="flex justify-between gap-4 pt-3">
					<dt class="text-muted-foreground">Next new moon</dt>
					<dd>{date(view.nextNewMoon)}</dd>
				</div>
			</dl>{/if}

		{#if !day && sourceLabel}<p class="text-[10px] text-muted-foreground">
				{sourceLabel} · {date(view.date)}
			</p>{/if}
	</Card.Content>
{/snippet}

<Card.Root
	style="container-type: inline-size"
	size={size === 'sm' ? 'sm' : 'default'}
	data-density={density}
	data-card-size={size}
	class={`relative isolate min-w-0 overflow-hidden ${className}`}
>
	<ForecastScreens
		{interactive}
		{days}
		title="Moon"
		{density}
		{sourceLabel}
		{iconType}
		actionLabel="Next 7 phases"
		summaryTitle="Next 7 phases"
	>
		{#snippet summary(availableHeight)}
			<div
				class="grid h-full auto-rows-[minmax(32px,1fr)] overflow-y-auto"
				data-slot="upcoming-moon-phases"
			>
				{#each phases as phase}
					<div class="flex min-h-0 items-center gap-3 border-b text-xs last:border-0">
						<div
							class="shrink-0"
							style={`width: ${Math.max(16, Math.min(32, availableHeight / 7 - 4))}px`}
						>
							<MoonDisc phase={phase.phase} label={phase.phaseName} class="size-full" />
						</div>
						<span class="min-w-0 flex-1 font-medium">{phase.phaseName}</span>
						<time datetime={phase.date} class="shrink-0 text-muted-foreground"
							>{date(phase.date)}</time
						>
					</div>
				{/each}
			</div>
		{/snippet}
		{#snippet children(openDay, action, visible)}
			{@render cardView(undefined, action)}
		{/snippet}
		{#snippet detail(day, action)}
			{@render cardView(day, action)}
		{/snippet}
	</ForecastScreens>
</Card.Root>

<style>
	:global([data-density='compact']) .moon-data > div {
		padding-block: 0.4rem;
	}
</style>

// packages/react/src/components/wxcn/moon-forecast.tsx
'use client';

import * as React from 'react';
import type { IconSet } from '../../icons/forecast-icons';

import { forecastDays, type ForecastDay } from '@wxcn/core/forecast-days.js';
import type { ForecastType, LocationInput, MoonForecast as MoonData } from '@wxcn/core/types.js';
import { getMoonForecast, getUpcomingMoonPhases, sampleMoon } from '@wxcn/core/moon.js';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { cn } from '@/lib/utils';
import { ForecastScreens } from './forecast-screens';
import MoonDisc from './moon-disc';

export type MoonForecastProps = {
	iconType?: IconSet;
	interactive?: boolean;
	timeZone?: string;
	type?: ForecastType;
	size?: 'sm' | 'default' | 'lg';
	density?: 'compact' | 'comfortable';
	className?: string;
	location?: LocationInput;
	forecast?: MoonData;
	sourceLabel?: string;
};

const defaultLocation: LocationInput = {
	label: 'Austin, TX',
	latitude: 30.2672,
	longitude: -97.7431
};

function MoonCardView({
	day,
	action,
	forecast,
	date,
	type,
	size,
	density,
	sourceLabel,
	location
}: {
	day?: ForecastDay;
	action?: React.ReactNode;
	forecast: MoonData;
	date: (value: string) => string;
	type: ForecastType;
	size: 'sm' | 'default' | 'lg';
	density: 'compact' | 'comfortable';
	sourceLabel: string;
	location: LocationInput;
}) {
	const view =
		day && day.entries[0].time !== Date.parse(forecast.date)
			? getMoonForecast(new Date(day.entries[0].time))
			: forecast;
	return (
		<>
			<CardHeader>
				<CardTitle>{day?.label ?? 'Moon phase'}</CardTitle>
				<CardDescription>{location.label}</CardDescription>
				{action}
			</CardHeader>
			<CardContent
				className={cn(
					'grid px-[var(--card-spacing,var(--wxcn-spacing))]',
					density === 'compact' ? 'gap-3' : 'gap-5'
				)}
			>
				<div
					className={cn(
						'flex items-center gap-4',
						size === 'lg' && 'flex-col rounded-lg bg-muted/20 p-5 text-center'
					)}
				>
					<MoonDisc
						phase={view.phase ?? view.age / 29.530588853}
						label={`${view.phaseName}, ${view.illumination}% illuminated`}
						className={
							size === 'sm'
								? 'size-16 shrink-0'
								: size === 'lg'
									? 'size-36 shrink-0'
									: 'size-24 max-w-[28cqw] shrink-0'
						}
					/>
					<div>
						<p
							style={{ fontSize: 'clamp(1rem,6cqw,1.5rem)' }}
							className={cn('font-medium tracking-tight', size === 'sm' ? 'text-lg' : 'text-2xl')}
						>
							{view.phaseName}
						</p>
						<p className="mt-2 text-sm text-muted-foreground">{view.illumination}% illuminated</p>
					</div>
				</div>
				{type !== 'simple' && (
					<dl className="moon-data divide-y text-sm">
						<div
							className={cn(
								'flex justify-between gap-4 pb-3',
								density === 'compact' && 'py-[0.4rem]'
							)}
						>
							<dt className="text-muted-foreground">Moon age</dt>
							<dd>{view.age} days</dd>
						</div>
						<div
							className={cn(
								'flex justify-between gap-4 py-3',
								density === 'compact' && 'py-[0.4rem]'
							)}
						>
							<dt className="text-muted-foreground">Next full moon</dt>
							<dd>{date(view.nextFullMoon)}</dd>
						</div>
						<div
							className={cn(
								'flex justify-between gap-4 pt-3',
								density === 'compact' && 'py-[0.4rem]'
							)}
						>
							<dt className="text-muted-foreground">Next new moon</dt>
							<dd>{date(view.nextNewMoon)}</dd>
						</div>
					</dl>
				)}
				{!day && sourceLabel && (
					<p className="text-[10px] text-muted-foreground">
						{sourceLabel} · {date(view.date)}
					</p>
				)}
			</CardContent>
		</>
	);
}

export function MoonForecast({
	iconType,
	interactive = false,
	timeZone,
	type = 'summary',
	size = 'default',
	density = 'comfortable',
	className,
	location = defaultLocation,
	forecast = sampleMoon,
	sourceLabel = ''
}: MoonForecastProps) {
	const [visitorTimeZone, setVisitorTimeZone] = React.useState('UTC');
	React.useEffect(() => setVisitorTimeZone(Intl.DateTimeFormat().resolvedOptions().timeZone), []);
	const displayTimeZone = timeZone ?? location.timeZone ?? visitorTimeZone;
	const date = React.useCallback(
		(value: string) =>
			new Intl.DateTimeFormat('en-US', {
				month: 'short',
				day: 'numeric',
				timeZone: displayTimeZone
			}).format(new Date(value)),
		[displayTimeZone]
	);
	const phases = React.useMemo(
		() => getUpcomingMoonPhases(new Date(forecast.date)),
		[forecast.date]
	);
	const days = React.useMemo(
		() =>
			forecastDays(
				phases.map((value) => ({
					time: Date.parse(value.date),
					label: value.phaseName,
					summary: `${value.illumination}% illuminated`,
					details: ''
				})),
				displayTimeZone
			),
		[displayTimeZone, phases]
	);

	return (
		<Card
			style={
				{
					containerType: 'inline-size',
					['--wxcn-spacing' as string]: size === 'sm' ? '1rem' : '1.5rem'
				} as React.CSSProperties
			}
			data-density={density}
			data-card-size={size}
			data-size={size === 'sm' ? 'sm' : 'default'}
			className={cn('relative isolate min-w-0 overflow-hidden', className)}
		>
			<ForecastScreens
				interactive={interactive}
				iconType={iconType}
				days={days}
				title="Moon"
				density={density}
				sourceLabel={sourceLabel}
				actionLabel="Next phases"
				summaryTitle="Next phases"
				summary={(availableHeight) => (
					<div
						className="grid h-full auto-rows-[minmax(32px,1fr)] overflow-y-auto"
						data-slot="upcoming-moon-phases"
					>
						{phases.map((phase) => (
							<div
								key={phase.date}
								className="flex min-h-0 items-center gap-3 border-b text-xs last:border-0"
							>
								<div
									className="shrink-0"
									style={{ width: Math.max(16, Math.min(32, availableHeight / 7 - 4)) }}
								>
									<MoonDisc phase={phase.phase} label={phase.phaseName} className="size-full" />
								</div>
								<span className="min-w-0 flex-1 font-medium">{phase.phaseName}</span>
								<time dateTime={phase.date} className="shrink-0 text-muted-foreground">
									{date(phase.date)}
								</time>
							</div>
						))}
					</div>
				)}
				detail={(day, action) => (
					<MoonCardView
						day={day}
						forecast={forecast}
						date={date}
						type={type}
						size={size}
						density={density}
						sourceLabel={sourceLabel}
						location={location}
						action={action(false)}
					/>
				)}
			>
				{(_openDay, action) => (
					<MoonCardView
						forecast={forecast}
						date={date}
						type={type}
						size={size}
						density={density}
						sourceLabel={sourceLabel}
						location={location}
						action={action(false)}
					/>
				)}
			</ForecastScreens>
		</Card>
	);
}

export default MoonForecast;
