// src/lib/components/wxcn/WeatherForecast.svelte
<script lang="ts">
	import * as Card from '$lib/components/ui/card/index.js';
	import { Badge } from '$lib/components/ui/badge/index.js';
	import ForecastIcon from '$lib/icons/forecast-icons.svelte';
	import WeatherShaderBackground, {
		type WeatherShaderMode
	} from './WeatherShaderBackground.svelte';
	import type {
		ForecastType,
		IconSet,
		LocationInput,
		WeatherPeriod,
		WeatherUnit
	} from '$lib/data/types.js';
	import { sampleWeather, convertWindSpeed } from '$lib/data/weather.js';
	let {
		type = 'summary',
		size = 'default',
		density = 'comfortable',
		class: className = '',
		unit = 'fahrenheit',
		iconType,
		location = { label: 'Austin, TX', latitude: 30.2672, longitude: -97.7431 },
		forecast = sampleWeather,
		sourceLabel = 'Sample forecast · Austin, TX',
		windUnit = 'mph',
		animatedBackground = false
	}: {
		type?: ForecastType;
		size?: 'sm' | 'default' | 'lg';
		density?: 'compact' | 'comfortable';
		class?: string;
		unit?: WeatherUnit;
		iconType?: IconSet;
		location?: LocationInput;
		forecast?: WeatherPeriod[];
		sourceLabel?: string;
		windUnit?: 'mph' | 'km/h' | 'm/s' | 'knots';
		animatedBackground?: boolean;
	} = $props();
	const current = $derived(forecast[0]);
	const periods = $derived(
		forecast.slice(1, type === 'detailed' ? 8 : density === 'compact' ? 3 : 5)
	);
	function temperature(p: WeatherPeriod) {
		return Math.round(
			unit === 'celsius' && p.temperatureUnit === 'F'
				? ((p.temperature - 32) * 5) / 9
				: unit === 'fahrenheit' && p.temperatureUnit === 'C'
					? (p.temperature * 9) / 5 + 32
					: p.temperature
		);
	}
	function condition(p: WeatherPeriod): WeatherShaderMode {
		const s = p.shortForecast.toLowerCase();
		if (/thunder|storm/.test(s)) return 'thunderstorm';
		if (/sleet|freezing|wintry/.test(s)) return 'wintry-mix';
		if (/snow/.test(s)) return s.includes('heavy') ? 'heavy-snow' : 'snow';
		if (/drizzle/.test(s)) return p.isDaytime ? 'drizzle' : 'drizzle-night';
		if (/rain|shower/.test(s)) return s.includes('heavy') ? 'heavy-rain' : 'rain';
		if (/fog/.test(s)) return 'fog';
		if (/haze|smoke/.test(s)) return 'haze';
		if (/partly|mostly sunny/.test(s)) return p.isDaytime ? 'partly-cloudy' : 'partly-cloudy-night';
		if (/cloud|overcast/.test(s)) return 'cloudy';
		if (/wind|breezy/.test(s)) return 'wind';
		return p.isDaytime ? 'clear' : 'clear-night';
	}
	function icon(p: WeatherPeriod) {
		const c = condition(p);
		return c.includes('rain') || c.includes('drizzle') || c === 'thunderstorm'
			? 'rain'
			: c.includes('snow') || c === 'wintry-mix'
				? 'snow'
				: c.includes('night')
					? 'moon'
					: c === 'clear'
						? 'sun'
						: 'weather';
	}
</script>

<Card.Root
	style="container-type: inline-size"
	size={size === 'sm' ? 'sm' : 'default'}
	data-density={density}
	data-card-size={size}
	class={`relative isolate min-w-0 overflow-hidden ${className}`}
>
	<Card.Header>
		<Card.Title>Weather</Card.Title>
		<Card.Description>{location.label ?? 'Local forecast'}</Card.Description>
		<Card.Action
			><ForecastIcon
				name="weather"
				iconSet={iconType}
				class="size-5 text-muted-foreground"
			/></Card.Action
		>
	</Card.Header>
	{#if current}
		<Card.Content class={density === 'compact' ? 'grid gap-3' : 'grid gap-6'}>
			<div
				class={`relative isolate overflow-hidden rounded-lg border bg-muted/20 ${size === 'sm' ? 'p-3' : size === 'lg' ? 'p-6' : 'p-5'}`}
			>
				{#if animatedBackground}<div
						class="pointer-events-none absolute inset-0 -z-10"
						aria-hidden="true"
					>
						<WeatherShaderBackground mode={condition(current)} />
					</div>{/if}
				{#if animatedBackground}<div
						class="pointer-events-none absolute inset-0 bg-linear-to-r from-black/55 via-black/25 to-black/10"
						aria-hidden="true"
					></div>{/if}
				<div
					class={`relative z-10 ${animatedBackground ? 'text-white [text-shadow:0_1px_5px_rgb(0_0_0/35%)]' : 'text-card-foreground'}`}
				>
					<p
						class={`mb-2 text-xs ${animatedBackground ? 'text-white/80' : 'text-muted-foreground'}`}
					>
						{current.name}
					</p>
					<p
						style="font-size:clamp(2rem,16cqw,4.5rem)"
						class={`font-medium tracking-tighter tabular-nums ${size === 'sm' ? 'text-4xl' : size === 'lg' ? 'text-7xl' : 'text-6xl'}`}
					>
						{temperature(current)}<span class="align-top text-3xl"
							>°{unit === 'celsius' ? 'C' : 'F'}</span
						>
					</p>
					<p class="mt-2 text-sm">{current.shortForecast}</p>
				</div>

				<div
					class={`relative z-10 mt-5 flex flex-wrap items-center justify-between gap-3 text-xs ${animatedBackground ? 'text-white' : 'text-card-foreground'}`}
				>
					<span class="flex items-center gap-2 opacity-80"
						><ForecastIcon name="wind" iconSet={iconType} class="size-4" />Wind</span
					><span class="tabular-nums"
						>{current.windDirection} {convertWindSpeed(current.windSpeed, windUnit)}</span
					>
				</div>
			</div>
			{#if type !== 'simple'}
				<div class="divide-y border-t">
					{#each periods as period, index (`${period.startTime}-${index}`)}
						<div
							class={`grid grid-cols-[1fr_auto_auto] items-center gap-4 text-sm ${density === 'compact' ? 'py-2' : 'py-3'}`}
						>
							<div>
								<p>{period.name}</p>
								{#if type === 'detailed'}<p
										class="mt-1 max-w-72 text-xs leading-5 text-muted-foreground"
									>
										{period.detailedForecast}
									</p>{/if}
							</div>
							<ForecastIcon
								name={icon(period)}
								iconSet={iconType}
								class="size-4 text-muted-foreground"
							/>
							<span class="min-w-9 text-right tabular-nums">{temperature(period)}°</span>
						</div>
					{/each}
				</div>
			{/if}
		</Card.Content>
	{:else}
		<Card.Content
			><p role="status" class="py-8 text-center text-sm text-muted-foreground">
				No forecast available. Try again later.
			</p></Card.Content
		>
	{/if}
	<Card.Footer class="justify-between gap-3 border-t text-xs text-muted-foreground"
		><span>{sourceLabel}</span><Badge variant="outline">{unit === 'celsius' ? '°C' : '°F'}</Badge
		></Card.Footer
	>
</Card.Root>

// packages/react/src/components/wxcn/weather-forecast.tsx
'use client';

import { useEffect, useState } from 'react';
import { ForecastIcon, type IconSet, type IconName } from '../../icons/forecast-icons';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { cn } from '@/lib/utils';
import { WeatherShaderBackground, type WeatherShaderMode } from './weather-shader-background';
import type {
	ForecastType,
	LocationInput,
	WeatherPeriod,
	CurrentWeather,
	WeatherUnit
} from '@wxcn/core/types.js';
import { sampleWeather, sampleCurrentWeather, convertWindSpeed } from '@wxcn/core/weather.js';
import { weatherOutlook } from '@wxcn/core/weather-outlook.js';

export interface WeatherForecastProps {
	iconType?: IconSet;
	timeZone?: string;
	type?: ForecastType;
	size?: 'sm' | 'default' | 'lg';
	density?: 'compact' | 'comfortable';
	className?: string;
	unit?: WeatherUnit;
	location?: LocationInput;
	forecast?: WeatherPeriod[];
	currentWeather?: CurrentWeather | null;
	showTemperatureTrend?: boolean;
	showHighLow?: boolean;
	at?: number;
	sourceLabel?: string;
	windUnit?: 'mph' | 'km/h' | 'm/s' | 'knots';
	animatedBackground?: boolean;
}

function condition(p: WeatherPeriod): WeatherShaderMode {
	const s = p.shortForecast.toLowerCase();
	if (/thunder|storm/.test(s)) return 'thunderstorm';
	if (/sleet|freezing|wintry/.test(s)) return 'wintry-mix';
	if (/snow/.test(s)) return s.includes('heavy') ? 'heavy-snow' : 'snow';
	if (/drizzle/.test(s)) return p.isDaytime ? 'drizzle' : 'drizzle-night';
	if (/rain|shower/.test(s)) return s.includes('heavy') ? 'heavy-rain' : 'rain';
	if (/fog/.test(s)) return 'fog';
	if (/haze|smoke/.test(s)) return 'haze';
	if (/partly|mostly sunny/.test(s)) return p.isDaytime ? 'partly-cloudy' : 'partly-cloudy-night';
	if (/cloud|overcast/.test(s)) return 'cloudy';
	if (/wind|breezy/.test(s)) return 'wind';
	return p.isDaytime ? 'clear' : 'clear-night';
}
function periodIcon(p: WeatherPeriod): IconName {
	const c = condition(p);
	return c.includes('rain') || c.includes('drizzle') || c === 'thunderstorm'
		? 'rain'
		: c.includes('snow') || c === 'wintry-mix'
			? 'snow'
			: c.includes('night')
				? 'moon'
				: c === 'clear'
					? 'sun'
					: 'weather';
}

export function WeatherForecast({
	iconType,
	timeZone,
	type = 'summary',
	size = 'default',
	density = 'comfortable',
	className,
	unit = 'fahrenheit',
	location = {
		label: 'Austin, TX',
		latitude: 30.2672,
		longitude: -97.7431,
		timeZone: 'America/Chicago'
	},
	forecast = sampleWeather,
	currentWeather = forecast === sampleWeather ? sampleCurrentWeather : null,
	showTemperatureTrend = false,
	showHighLow = false,
	at,
	sourceLabel = forecast === sampleWeather ? 'Sample forecast' : '',
	windUnit = 'mph',
	animatedBackground = false
}: WeatherForecastProps) {
	const [visitorTimeZone, setVisitorTimeZone] = useState('UTC');
	const [clock, setClock] = useState<number | null>(null);
	useEffect(() => {
		setVisitorTimeZone(Intl.DateTimeFormat().resolvedOptions().timeZone);
		setClock(Date.now());
		const timer = setInterval(() => setClock(Date.now()), 60000);
		return () => clearInterval(timer);
	}, []);
	const effectiveTime =
		at ?? (forecast === sampleWeather ? Date.parse(sampleCurrentWeather.observedAt) : (clock ?? 0));
	const outlook = weatherOutlook(
		currentWeather,
		forecast,
		unit,
		timeZone ?? visitorTimeZone,
		effectiveTime
	);
	const periods = forecast.slice(0, type === 'detailed' ? 8 : density === 'compact' ? 3 : 5);
	const current = currentWeather;
	const temperature = (p: WeatherPeriod) =>
		Math.round(
			unit === 'celsius' && p.temperatureUnit === 'F'
				? ((p.temperature - 32) * 5) / 9
				: unit === 'fahrenheit' && p.temperatureUnit === 'C'
					? (p.temperature * 9) / 5 + 32
					: p.temperature
		);
	if (
		forecast !== sampleWeather &&
		(forecast.length > 0 || currentWeather) &&
		at === undefined &&
		clock === null
	) {
		return (
			<Card className={className}>
				<CardHeader>
					<CardTitle>Weather</CardTitle>
					<CardDescription>{location.label}</CardDescription>
				</CardHeader>
				<CardContent>
					<p role="status">Loading current weather time…</p>
				</CardContent>
			</Card>
		);
	}
	return (
		<Card
			data-density={density}
			style={
				{
					containerType: 'inline-size',
					'--wxcn-spacing': size === 'sm' ? '1rem' : '1.5rem'
				} as import('react').CSSProperties
			}
			data-card-size={size}
			data-size={size === 'sm' ? 'sm' : 'default'}
			className={cn(
				'relative isolate min-w-0 gap-0 overflow-hidden py-0',

				className
			)}
		>
			<div
				className={cn(
					'relative isolate overflow-hidden',
					animatedBackground && current ? 'text-white' : 'text-card-foreground'
				)}
			>
				{animatedBackground && current && (
					<>
						<div className="pointer-events-none absolute inset-0 -z-10" aria-hidden="true">
							<WeatherShaderBackground mode={condition(current)} />
						</div>
						<div
							className="pointer-events-none absolute inset-0 -z-10 bg-linear-to-b from-black/35 via-black/15 to-black/55"
							aria-hidden="true"
						/>
					</>
				)}
				<CardHeader className="relative px-[var(--card-spacing,var(--wxcn-spacing))] pt-[var(--card-spacing,var(--wxcn-spacing))]">
					<CardTitle>Weather</CardTitle>
					<CardDescription className={animatedBackground && current ? 'text-white/80' : ''}>
						{location.label ?? 'Local forecast'}
					</CardDescription>
				</CardHeader>
				<CardContent className="relative grid gap-5 px-[var(--card-spacing,var(--wxcn-spacing))] py-[var(--card-spacing,var(--wxcn-spacing))]">
					{current ? (
						<>
							<div>
								<p
									className={cn(
										'mb-2 text-xs',
										animatedBackground ? 'text-white/75' : 'text-muted-foreground'
									)}
								>
									Now
								</p>
								<p
									style={{ fontSize: 'clamp(2.5rem,18cqw,5rem)' }}
									className="leading-none font-medium tracking-tighter tabular-nums"
								>
									{temperature(current)}
									<span className="align-top text-2xl">°</span>
								</p>
								<p className="mt-3 text-sm">{current.shortForecast}</p>
								{showTemperatureTrend && outlook.trend && (
									<p className="mt-2 text-sm" data-slot="temperature-trend">
										{outlook.trend}
									</p>
								)}
								{showHighLow && (
									<div
										className="mt-3 flex gap-4 text-sm tabular-nums"
										data-slot="temperature-range"
									>
										{outlook.high !== null && (
											<span aria-label={`High ${outlook.high} degrees`}>
												<ForecastIcon
													name="arrowUp"
													iconSet={iconType}
													className="inline size-3.5"
												/>{' '}
												{outlook.high}°
											</span>
										)}
										{outlook.low !== null && (
											<span aria-label={`Low ${outlook.low} degrees`}>
												<ForecastIcon
													name="arrowDown"
													iconSet={iconType}
													className="inline size-3.5"
												/>{' '}
												{outlook.low}°
											</span>
										)}
									</div>
								)}
							</div>
							<div className="flex flex-wrap items-center justify-between gap-3 text-xs">
								<span className="flex items-center gap-2 opacity-80">
									<ForecastIcon name="wind" iconSet={iconType} className="size-4" />
									Wind
								</span>
								<span className="tabular-nums">
									{current.windDirection} {convertWindSpeed(current.windSpeed, windUnit)}
								</span>
							</div>
						</>
					) : (
						<p role="status" className="py-8 text-center text-sm text-muted-foreground">
							Current conditions unavailable.
						</p>
					)}
					{type === 'simple' && sourceLabel && (
						<p
							className={cn(
								'text-[10px]',
								animatedBackground && current ? 'text-white/70' : 'text-muted-foreground'
							)}
						>
							{sourceLabel}
						</p>
					)}
				</CardContent>
			</div>
			{type !== 'simple' && (
				<CardContent className="px-[var(--card-spacing,var(--wxcn-spacing))] pb-[var(--card-spacing,var(--wxcn-spacing))]">
					{periods.length > 0 && (
						<div className="divide-y">
							{periods.map((period, index) => {
								const icon = periodIcon(period);
								return (
									<div
										key={`${period.startTime}-${index}`}
										className={cn(
											'grid grid-cols-[minmax(0,1fr)_auto_auto] items-center gap-3 text-sm',
											density === 'compact' ? 'py-2' : 'py-3'
										)}
									>
										<div>
											<p>{period.name}</p>
											{type === 'detailed' && (
												<p className="mt-1 text-xs leading-5 text-muted-foreground">
													{period.detailedForecast}
												</p>
											)}
										</div>
										<ForecastIcon
											name={icon}
											iconSet={iconType}
											className="size-4 text-muted-foreground"
										/>
										<span className="min-w-9 text-right tabular-nums">{temperature(period)}°</span>
									</div>
								);
							})}
						</div>
					)}
					{sourceLabel && <p className="mt-2 text-[10px] text-muted-foreground">{sourceLabel}</p>}
				</CardContent>
			)}
		</Card>
	);
}
