// packages/vue/src/components/wxcn/TideForecast.vue
<script setup lang="ts">
import {
	computed,
	defineComponent,
	h,
	onBeforeUnmount,
	onMounted,
	ref,
	type PropType,
	type VNodeRef
} from 'vue';
import NumberFlow from '@number-flow/vue';
import { area as shapeArea, curveMonotoneX, line as shapeLine } from 'd3-shape';
import { forecastDays, type ForecastDay } from '@wxcn/core/forecast-days.js';
import { sampleTideSeries, sampleTideTime, sampleTides } from '@wxcn/core/tides.js';
import { tideState, tideTimestamp } from '@wxcn/core/tide-state.js';
import type {
	ForecastType,
	LocationInput,
	TidePoint,
	TidePrediction,
	TideReading,
	TideUnit
} from '@wxcn/core/types.js';
import ForecastIcon, { type IconSet } from '../../icons/ForecastIcon.vue';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../ui/card';
import ForecastScreens from './ForecastScreens.vue';

type Point = { time: number; height: number };
type OpenDay = (time: string, trigger: HTMLElement) => void;
const props = withDefaults(
	defineProps<{
		interactive?: boolean;
		iconType?: IconSet;
		timeZone?: string;
		type?: ForecastType;
		size?: 'sm' | 'default' | 'lg';
		density?: 'compact' | 'comfortable';
		class?: string;
		unit?: TideUnit;
		location?: LocationInput;
		predictions?: TidePrediction[];
		example?: boolean;
		series?: TidePoint[];
		reading?: TideReading | null;
		at?: number;
		sourceLabel?: string;
	}>(),
	{
		interactive: false,
		type: 'summary',
		size: 'default',
		density: 'comfortable',
		class: '',
		unit: 'ft',
		location: () => ({
			label: 'Galveston Pier 21, TX',
			latitude: 29.31,
			longitude: -94.7933,
			station: '8771450',
			timeZone: 'America/Chicago'
		}),
		predictions: () => sampleTides,
		reading: null,
		sourceLabel: 'Sample tides'
	}
);
const visitor = ref('UTC'),
	clock = ref<number | null>(null),
	hovered = ref<Point | null>(null),
	dayHovered = ref<Point | null>(null);
let timer: number | undefined;
onMounted(() => {
	visitor.value = Intl.DateTimeFormat().resolvedOptions().timeZone;
	clock.value = Date.now();
	timer = window.setInterval(() => (clock.value = Date.now()), 60_000);
});
onBeforeUnmount(() => clearInterval(timer));
const zone = computed(() => props.timeZone ?? props.location.timeZone ?? visitor.value),
	sample = computed(() => props.example ?? props.predictions === sampleTides),
	now = computed(() => props.at ?? (sample.value ? sampleTideTime : (clock.value ?? 0)));
const tide = computed(() =>
	tideState(
		props.predictions,
		props.series ?? (sample.value ? sampleTideSeries : []),
		props.reading,
		now.value
	)
);
const symbol = computed(() => (props.unit === 'meter' ? 'm' : 'ft')),
	level = (n: number) => (n * (props.unit === 'meter' ? 0.3048 : 1)).toFixed(1);
const time = (v: string | number) =>
	new Intl.DateTimeFormat('en-US', {
		hour: 'numeric',
		minute: '2-digit',
		timeZone: zone.value
	}).format(typeof v === 'string' ? tideTimestamp(v) : v);
const dateTime = (v: string) =>
	new Intl.DateTimeFormat('en-US', {
		month: 'short',
		day: 'numeric',
		hour: 'numeric',
		minute: '2-digit',
		timeZone: zone.value
	}).format(tideTimestamp(v));
const chartData = computed<Point[]>(() => {
	const data = tide.value.points.filter(
		(p) => p.time >= now.value - 12 * 36e5 && p.time <= now.value + 18 * 36e5
	);
	return tide.value.predicted !== null && !data.some((p) => p.time === now.value)
		? [...data, { time: now.value, height: tide.value.predicted }].sort((a, b) => a.time - b.time)
		: data;
});
const days = computed(() =>
	forecastDays(
		tide.value.events
			.filter((e) => {
				const t = tideTimestamp(e.time);
				return t >= now.value && t < now.value + 7 * 864e5;
			})
			.map((e) => ({
				time: tideTimestamp(e.time),
				label: time(e.time),
				summary: `${e.type === 'H' ? 'High' : 'Low'} tide · ${level(+e.height)} ${symbol.value}`,
				details: `Predicted ${e.type === 'H' ? 'high' : 'low'} tide, ${level(+e.height)} ${symbol.value} above MLLW.`
			})),
		zone.value
	)
);
function pointsForDay(day: ForecastDay) {
	const key = new Intl.DateTimeFormat('en-CA', {
		timeZone: zone.value,
		year: 'numeric',
		month: '2-digit',
		day: '2-digit'
	});
	return tide.value.points.filter((p) => key.format(p.time) === day.key);
}
function domain(data: Point[], extra: number | null = null): [number, number] {
	const v = data.map((p) => p.height);
	if (extra !== null) v.push(extra);
	if (!v.length) return [0, 1];
	const lo = Math.min(...v),
		hi = Math.max(...v),
		pad = Math.max(0.15, (hi - lo) * 0.2);
	return [lo - pad, hi + pad];
}

const TideView = defineComponent({
	props: { day: Object as PropType<ForecastDay>, openDay: Function as PropType<OpenDay> },
	setup(p) {
		const chartSize = ref({ width: 320, height: 112 });
		let chartObserver: ResizeObserver | undefined;
		const setChartElement: VNodeRef = (value) => {
			const element = value instanceof SVGSVGElement ? value : null;
			chartObserver?.disconnect();
			if (!element) return;
			const measure = () => {
				const bounds = element.getBoundingClientRect();
				if (
					bounds.width > 0 &&
					bounds.height > 0 &&
					(Math.abs(bounds.width - chartSize.value.width) > 0.1 ||
						Math.abs(bounds.height - chartSize.value.height) > 0.1)
				) {
					chartSize.value = { width: bounds.width, height: bounds.height };
				}
			};
			chartObserver = new ResizeObserver(measure);
			chartObserver.observe(element);
			measure();
		};
		onBeforeUnmount(() => chartObserver?.disconnect());
		return () => {
			const day = p.day,
				events = day
					? tide.value.events.filter((e) =>
							day.entries.some((x) => x.time === tideTimestamp(e.time))
						)
					: props.predictions,
				viewNow = day ? day.entries[0].time : now.value,
				viewTide = day
					? tideState(events, props.series ?? (sample.value ? sampleTideSeries : []), null, viewNow)
					: tide.value,
				data = day ? pointsForDay(day) : chartData.value,
				hover = day ? dayHovered : hovered,
				selected =
					hover.value && data.some((x) => x.time === hover.value?.time) ? hover.value : null,
				displayLevel = selected?.height ?? viewTide.level,
				displayTime =
					selected?.time ??
					(day ? viewNow : viewTide.observed ? tideTimestamp(viewTide.observed.time) : now.value),
				indicatorTime = selected?.time ?? (day ? displayTime : now.value),
				indicatorLevel = selected?.height ?? viewTide.predicted,
				d = domain(data, day ? null : tide.value.level),
				W = chartSize.value.width,
				H = chartSize.value.height,
				x0 = data[0]?.time ?? 0,
				x1 = data.at(-1)?.time ?? 1,
				x = (v: number) => 8 + ((v - x0) / (x1 - x0 || 1)) * (W - 16),
				y = (v: number) => 8 + ((d[1] - v) / (d[1] - d[0] || 1)) * (H - 12);
			const path =
				shapeLine<Point>()
					.x((point) => x(point.time))
					.y((point) => y(point.height))
					.curve(curveMonotoneX)(data) ?? '';
			const fillPath =
				shapeArea<Point>()
					.x((point) => x(point.time))
					.y0(H)
					.y1((point) => y(point.height))
					.curve(curveMonotoneX)(data) ?? '';
			function nearest(clientX: number, svg: SVGSVGElement) {
				const r = svg.getBoundingClientRect(),
					position = Math.max(0, Math.min(1, (clientX - r.left - 8) / Math.max(1, r.width - 16))),
					t = x0 + position * (x1 - x0);
				hover.value = data.reduce((a, b) => (Math.abs(b.time - t) < Math.abs(a.time - t) ? b : a));
			}
			function key(e: KeyboardEvent) {
				if (!['ArrowLeft', 'ArrowRight', 'Home', 'End', 'Escape'].includes(e.key)) return;
				e.preventDefault();
				if (e.key === 'Escape') {
					hover.value = null;
					return;
				}
				let i = hover.value
					? data.findIndex((q) => q.time === hover.value?.time)
					: e.key === 'ArrowLeft' || e.key === 'End'
						? data.length - 1
						: 0;
				if (e.key === 'ArrowLeft') i--;
				if (e.key === 'ArrowRight') i++;
				if (e.key === 'Home') i = 0;
				if (e.key === 'End') i = data.length - 1;
				hover.value = data[Math.max(0, Math.min(data.length - 1, i))];
			}
			const parts = new Intl.DateTimeFormat('en-US', {
				hour: 'numeric',
				minute: '2-digit',
				timeZone: zone.value
			}).formatToParts(displayTime);
			const headline = h(
				'div',
				{ class: `flex items-end justify-between gap-3 ${day ? '' : 'flex-wrap'}` },
				[
					h('div', { class: 'min-w-0' }, [
						h(
							'p',
							{ class: `mb-1 text-xs text-muted-foreground ${day ? 'truncate' : ''}` },
							selected
								? 'Predicted water level'
								: !day && sample.value
									? 'Example water level'
									: viewTide.observed
										? 'Current water level'
										: viewTide.predicted !== null
											? 'Predicted water level'
											: 'High/low predictions only'
						),
						h(
							'p',
							{
								style: { fontSize: 'clamp(1.5rem, 12cqw, 2.5rem)' },
								class: `${props.size === 'sm' ? 'text-3xl' : 'text-4xl'} font-medium tracking-tight tabular-nums`
							},
							[
								displayLevel === null
									? '—'
									: h(NumberFlow, {
											value: +level(displayLevel),
											format: { minimumFractionDigits: 1, maximumFractionDigits: 1 }
										}),
								h('span', { class: 'ml-1 text-sm text-muted-foreground' }, symbol.value)
							]
						)
					]),
					h('div', { class: 'text-right text-xs text-muted-foreground' }, [
						h(
							'p',
							selected
								? 'Selected time'
								: viewTide.next
									? viewTide.next.type === 'H'
										? 'Rising toward high tide'
										: 'Falling toward low tide'
									: 'Tide outlook'
						),
						h('p', { class: 'mt-1 tabular-nums', 'data-slot': 'tide-time' }, [
							h('span', { class: 'sr-only' }, time(displayTime)),
							h(
								'span',
								{ 'aria-hidden': 'true' },
								parts.map((part, i) =>
									part.type === 'hour' || part.type === 'minute'
										? h(NumberFlow, {
												key: i,
												value: +part.value,
												format: {
													minimumIntegerDigits: part.type === 'minute' ? 2 : 1,
													useGrouping: false
												}
											})
										: part.value
								)
							)
						])
					])
				]
			);
			const graph =
				data.length > 1
					? h('div', [
							h('div', { class: 'relative' }, [
								h(
									'svg',
									{
										ref: setChartElement,
										viewBox: `0 0 ${W} ${H}`,
										preserveAspectRatio: 'none',
										class: `aspect-auto w-full overflow-visible ${props.size === 'sm' ? 'h-20' : props.size === 'lg' ? 'h-36' : 'h-28'}`,
										role: 'img',
										tabindex: 0,
										'aria-label':
											'Tide prediction curve with predicted water level marker. Use arrow keys to inspect points.',
										onPointermove: (e: PointerEvent) =>
											nearest(e.clientX, e.currentTarget as SVGSVGElement),
										onPointerleave: () => (hover.value = null),
										onFocus: () => {
											if (!hover.value)
												hover.value = data.reduce((a, b) =>
													Math.abs(b.time - indicatorTime) < Math.abs(a.time - indicatorTime)
														? b
														: a
												);
										},
										onBlur: () => (hover.value = null),
										onKeydown: key
									},
									[
										[0.25, 0.5, 0.75].map((r) =>
											h('line', {
												x1: 8,
												x2: W - 8,
												y1: H * r,
												y2: H * r,
												stroke: 'var(--border)',
												'stroke-dasharray': '3 4',
												'vector-effect': 'non-scaling-stroke'
											})
										),
										h('path', {
											d: fillPath,
											fill: 'var(--chart-1, var(--primary))',
											opacity: 0.12
										}),
										h('path', {
											d: path,
											fill: 'none',
											stroke: 'var(--chart-1, var(--primary))',
											'stroke-width': 2,
											'vector-effect': 'non-scaling-stroke'
										}),
										indicatorLevel !== null && indicatorTime >= x0 && indicatorTime <= x1
											? h('g', [
													h('line', {
														x1: x(indicatorTime),
														x2: x(indicatorTime),
														y1: 0,
														y2: H,
														stroke: 'var(--muted-foreground)',
														'stroke-dasharray': '3 4',
														'vector-effect': 'non-scaling-stroke'
													}),
													h('circle', {
														'data-slot': 'current-tide-marker',
														cx: x(indicatorTime),
														cy: y(indicatorLevel),
														r: 4.5,
														fill: 'var(--chart-1, var(--primary))',
														stroke: 'var(--card)',
														'stroke-width': 2,
														'vector-effect': 'non-scaling-stroke'
													})
												])
											: null
									]
								),
								selected
									? h(
											'div',
											{
												class:
													'pointer-events-none absolute top-1 z-10 rounded-md border bg-background px-2 py-1 text-[10px] shadow-sm',
												style: {
													left: `${(x(selected.time) / W) * 100}%`,
													transform:
														x(selected.time) > 720
															? 'translateX(-100%)'
															: x(selected.time) < 280
																? 'none'
																: 'translateX(-50%)'
												},
												role: 'status'
											},
											[
												h('p', { class: 'font-medium' }, time(selected.time)),
												h('p', `${level(selected.height)} ${symbol.value}`)
											]
										)
									: null
							]),
							h('div', { class: '-mt-2 flex justify-between text-[10px] text-muted-foreground' }, [
								h('span', time(data[0].time)),
								h('span', `MLLW · ${viewTide.points.length ? 'predicted curve' : 'extrema only'}`),
								h('span', time(data.at(-1)!.time))
							])
						])
					: null;
			const previousNext = h(
				'div',
				{ class: 'grid grid-cols-2 gap-3 border-t pt-3' },
				[
					{ label: 'Previous', event: viewTide.previous },
					{ label: 'Next', event: viewTide.next }
				].map(({ label: caption, event }) =>
					h('div', { key: caption }, [
						h(
							'p',
							{ class: 'text-xs text-muted-foreground' },
							`${caption} ${event ? (event.type === 'H' ? 'high tide' : 'low tide') : 'tide'}`
						),
						h(
							'p',
							{ class: 'mt-1 text-sm font-medium tabular-nums' },
							event ? time(event.time) : 'Unavailable'
						),
						event
							? h(
									'p',
									{ class: 'mt-1 text-xs text-muted-foreground' },
									`${level(+event.height)} ${symbol.value}`
								)
							: null
					])
				)
			);
			const list =
				props.type !== 'simple'
					? h(
							'div',
							{ class: 'divide-y border-t' },
							viewTide.events
								.filter((e) => tideTimestamp(e.time) > viewNow)
								.slice(0, props.type === 'detailed' ? 6 : props.density === 'compact' ? 2 : 4)
								.map((e) =>
									h(
										'div',
										{
											key: `${e.time}-${e.type}`,
											class: `flex justify-between gap-2 text-xs ${props.density === 'compact' ? 'py-2' : 'py-3'}`
										},
										[
											props.interactive && props.size !== 'lg' && !day
												? h(
														'button',
														{
															type: 'button',
															class:
																'min-h-8 text-left underline-offset-4 hover:underline focus-visible:outline-2 focus-visible:outline-ring',
															'aria-label': `View tide details for ${dateTime(e.time)}`,
															onClick: (v: MouseEvent) =>
																p.openDay?.(
																	new Date(tideTimestamp(e.time)).toISOString(),
																	v.currentTarget as HTMLElement
																)
														},
														e.type === 'H' ? 'High tide' : 'Low tide'
													)
												: h('span', e.type === 'H' ? 'High tide' : 'Low tide'),
											h('span', { class: 'ml-auto text-muted-foreground' }, dateTime(e.time)),
											h('span', { class: 'tabular-nums' }, `${level(+e.height)} ${symbol.value}`)
										]
									)
								)
						)
					: null;
			return [
				h(CardHeader, null, {
					default: () => [
						h(CardTitle, null, { default: () => day?.label ?? 'Tides' }),
						h(CardDescription, null, { default: () => props.location.label })
					]
				}),
				h(
					CardContent,
					{ class: props.density === 'compact' ? 'grid gap-3' : 'grid gap-5' },
					{
						default: () =>
							viewTide.events.length || viewTide.points.length
								? [
										headline,
										graph,
										previousNext,
										list,
										!day && props.sourceLabel
											? h('p', { class: 'text-[10px] text-muted-foreground' }, props.sourceLabel)
											: null
									]
								: [
										h(
											'p',
											{ role: 'status', class: 'py-8 text-center text-sm text-muted-foreground' },
											'No tide predictions available.'
										),
										!day && props.sourceLabel
											? h('p', { class: 'text-[10px] text-muted-foreground' }, props.sourceLabel)
											: null
									]
					}
				)
			];
		};
	}
});
const loading = computed(
	() =>
		!sample.value &&
		(props.predictions.length > 0 || (props.series?.length ?? 0) > 0) &&
		props.at === undefined &&
		clock.value === null
);
</script>
<template>
	<Card
		style="container-type: inline-size"
		:data-density="density"
		:data-card-size="size"
		:data-size="size === 'sm' ? 'sm' : 'default'"
		:class="['relative isolate min-w-0 overflow-hidden', props.class]"
	>
		<template v-if="loading"
			><CardHeader
				><CardTitle>Tides</CardTitle
				><CardDescription>{{ location.label }}</CardDescription></CardHeader
			><CardContent
				><p role="status" class="py-8 text-center text-sm text-muted-foreground">
					Loading current tide time…
				</p></CardContent
			></template
		>
		<ForecastScreens
			v-else
			:interactive="interactive && size !== 'lg'"
			:days="days"
			title="Tide"
			:density="density"
			:source-label="sourceLabel"
			:icon-type="iconType"
			show-week
			action-label="Upcoming tides"
			has-summary
		>
			<template #overview="{ openDay }"><TideView :open-day="openDay" /></template
			><template #detail="{ day }"><TideView :day="day" /></template>
			<template #summary="{ height: availableHeight }"
				><div class="divide-y" data-slot="upcoming-tides">
					<div
						v-for="event in tide.events
							.filter((e) => tideTimestamp(e.time) >= now)
							.slice(0, Math.max(1, Math.floor(availableHeight / 32)))"
						:key="`${event.time}-${event.type}`"
						class="flex h-8 items-center justify-between gap-2 text-xs"
					>
						<span class="flex shrink-0 items-center gap-1"
							><ForecastIcon
								:name="event.type === 'H' ? 'arrowUp' : 'arrowDown'"
								:icon-set="iconType"
								class="size-3"
							/>{{ event.type === 'H' ? 'High' : 'Low' }}</span
						><span class="truncate text-muted-foreground">{{ time(event.time) }}</span
						><span class="shrink-0 tabular-nums">{{ level(+event.height) }} {{ symbol }}</span>
					</div>
				</div></template
			>
		</ForecastScreens>
	</Card>
</template>

// packages/svelte/src/components/wxcn/TideForecast.svelte
<script lang="ts">
	import { onMount, type ComponentProps, type Snippet } from 'svelte';
	import NumberFlow from '@number-flow/svelte';
	import * as ChartUI from '../ui/chart/index.js';
	import { Chart, Svg, Area } from 'layerchart';
	import { curveMonotoneX } from 'd3-shape';
	import * as Card from '../ui/card/index.js';
	import ForecastIcon from '../../icons/forecast-icons.svelte';
	import ForecastScreens from './ForecastScreens.svelte';
	import { forecastDays, type ForecastDay } from '@wxcn/core/forecast-days.js';
	import type {
		ForecastType,
		IconSet,
		LocationInput,
		TidePrediction,
		TideUnit,
		TidePoint,
		TideReading
	} from '@wxcn/core/types.js';
	import { sampleTides, sampleTideSeries, sampleTideTime } from '@wxcn/core/tides.js';
	import { tideState, tideTimestamp } from '@wxcn/core/tide-state.js';
	let {
		interactive = false,
		timeZone,
		type = 'summary',
		size = 'default',
		density = 'comfortable',
		class: className = '',
		unit = 'ft',
		iconType,
		location = {
			label: 'Galveston Pier 21, TX',
			latitude: 29.31,
			longitude: -94.7933,
			station: '8771450',
			timeZone: 'America/Chicago'
		},
		predictions = sampleTides,
		example = predictions === sampleTides,
		series,
		reading = null,
		at,
		sourceLabel = 'Sample tides'
	}: {
		interactive?: boolean;
		timeZone?: string;
		type?: ForecastType;
		size?: 'sm' | 'default' | 'lg';
		density?: 'compact' | 'comfortable';
		class?: string;
		unit?: TideUnit;
		iconType?: IconSet;
		location?: LocationInput;
		predictions?: TidePrediction[];
		example?: boolean;
		series?: TidePoint[];
		reading?: TideReading | null;
		at?: number;
		sourceLabel?: string;
	} = $props();
	let visitorTimeZone = $state('UTC');
	onMount(() => {
		visitorTimeZone = Intl.DateTimeFormat().resolvedOptions().timeZone;
	});
	const displayTimeZone = $derived(timeZone ?? location.timeZone ?? visitorTimeZone);
	let clock = $state(Date.now());
	onMount(() => {
		clock = Date.now();
		const timer = setInterval(() => (clock = Date.now()), 60000);
		return () => clearInterval(timer);
	});
	const isSample = $derived(example);
	const now = $derived(at ?? (isSample ? sampleTideTime : clock));
	const tide = $derived(
		tideState(predictions, series ?? (isSample ? sampleTideSeries : []), reading, now)
	);
	const curveData = $derived(
		tide.points.filter((p) => p.time >= now - 12 * 3600000 && p.time <= now + 18 * 3600000)
	);
	// The curve is predicted; observations remain in the headline only.
	const markerTime = $derived(now);
	const chartData = $derived(
		tide.predicted !== null && !curveData.some((p) => p.time === now)
			? [...curveData, { time: now, height: tide.predicted }].toSorted((a, b) => a.time - b.time)
			: curveData
	);
	let chartContext = $state<ComponentProps<typeof Chart>['context']>();
	const hovered = $derived(
		chartContext?.tooltip.data as { time: number; height: number } | null | undefined
	);
	const displayedLevel = $derived(hovered?.height ?? tide.level);
	const displayedTime = $derived(
		hovered?.time ?? (tide.observed ? tideTimestamp(tide.observed.time) : now)
	);
	const indicatorTime = $derived(hovered?.time ?? markerTime);
	const indicatorLevel = $derived(hovered?.height ?? tide.predicted);
	const timeParts = $derived(
		new Intl.DateTimeFormat('en-US', {
			hour: 'numeric',
			minute: '2-digit',
			timeZone: displayTimeZone
		}).formatToParts(displayedTime)
	);
	const domain = $derived.by(() => {
		const v = chartData.map((p) => p.height);
		if (tide.level !== null) v.push(tide.level);
		const lo = Math.min(...v),
			hi = Math.max(...v);
		return [lo - Math.max(0.15, (hi - lo) * 0.2), hi + Math.max(0.15, (hi - lo) * 0.2)];
	});
	const height = (value: number) => (value * (unit === 'meter' ? 0.3048 : 1)).toFixed(1);
	const symbol = $derived(unit === 'meter' ? 'm' : 'ft');
	const time = (value: string | number) =>
		new Intl.DateTimeFormat('en-US', {
			hour: 'numeric',
			minute: '2-digit',
			timeZone: displayTimeZone
		}).format(typeof value === 'string' ? tideTimestamp(value) : value);
	const dateTime = (p: TidePrediction) =>
		new Intl.DateTimeFormat('en-US', {
			month: 'short',
			day: 'numeric',
			hour: 'numeric',
			minute: '2-digit',
			timeZone: displayTimeZone
		}).format(tideTimestamp(p.time));
	const days = $derived(
		forecastDays(
			tide.events
				.filter((p) => tideTimestamp(p.time) >= now && tideTimestamp(p.time) < now + 7 * 86400000)
				.map((p) => ({
					time: tideTimestamp(p.time),
					label: time(p.time),
					summary: `${p.type === 'H' ? 'High' : 'Low'} tide · ${height(Number(p.height))} ${symbol}`,
					details: `Predicted ${p.type === 'H' ? 'high' : 'low'} tide, ${height(Number(p.height))} ${symbol} above MLLW.`
				})),
			displayTimeZone
		)
	);

	let dayChartContext = $state<ComponentProps<typeof Chart>['context']>();
	function pointsForDay(day: ForecastDay) {
		const key = new Intl.DateTimeFormat('en-CA', {
			timeZone: displayTimeZone,
			year: 'numeric',
			month: '2-digit',
			day: '2-digit'
		});
		return tide.points.filter((point) => key.format(point.time) === day.key);
	}
	function dailyDomain(points: { time: number; height: number }[]) {
		const values = points.map((point) => point.height);
		if (!values.length) return [0, 1];
		const lo = Math.min(...values),
			hi = Math.max(...values),
			padding = Math.max(0.15, (hi - lo) * 0.2);
		return [lo - padding, hi + padding];
	}
</script>

{#snippet cardView(
	day: ForecastDay | undefined,
	action: Snippet<[boolean]>,
	openDay: (time: string, trigger: HTMLElement) => void
)}
	{@const events = day
		? tide.events.filter((event) =>
				day.entries.some((entry) => entry.time === tideTimestamp(event.time))
			)
		: predictions}
	{@const viewNow = day ? day.entries[0].time : now}
	{@const viewTide = day
		? tideState(events, series ?? (isSample ? sampleTideSeries : []), null, viewNow)
		: tide}
	{@const viewChartData = day ? pointsForDay(day) : chartData}
	{@const viewDomain = day ? dailyDomain(viewChartData) : domain}
	{@const viewHovered = day
		? (dayChartContext?.tooltip.data as { time: number; height: number } | undefined)
		: hovered}
	{@const viewDisplayedLevel = day ? (viewHovered?.height ?? viewTide.level) : displayedLevel}
	{@const viewDisplayedTime = day ? (viewHovered?.time ?? viewNow) : displayedTime}
	{@const viewTimeParts = day
		? new Intl.DateTimeFormat('en-US', {
				hour: 'numeric',
				minute: '2-digit',
				timeZone: displayTimeZone
			}).formatToParts(viewDisplayedTime)
		: timeParts}
	{@const viewIndicatorTime = day ? viewDisplayedTime : indicatorTime}
	{@const viewIndicatorLevel = day ? (viewHovered?.height ?? viewTide.predicted) : indicatorLevel}
	<Card.Header
		><Card.Title>{day?.label ?? 'Tides'}</Card.Title><Card.Description
			>{location.label}</Card.Description
		>{@render action(false)}</Card.Header
	>
	<Card.Content class={density === 'compact' ? 'grid gap-3' : 'grid gap-5'}>
		{#if viewTide.events.length || viewTide.points.length}
			<div class={`flex items-end justify-between gap-3 ${day ? '' : 'flex-wrap'}`}>
				<div class="min-w-0">
					<p class={`mb-1 text-xs text-muted-foreground ${day ? 'truncate' : ''}`}>
						{viewHovered
							? 'Predicted water level'
							: !day && isSample
								? 'Example water level'
								: viewTide.observed
									? 'Current water level'
									: viewTide.predicted !== null
										? 'Predicted water level'
										: 'High/low predictions only'}
					</p>
					<p
						style="font-size:clamp(1.5rem,12cqw,2.5rem)"
						class={`${size === 'sm' ? 'text-3xl' : 'text-4xl'} font-medium tracking-tight tabular-nums`}
					>
						{#if viewDisplayedLevel === null}—{:else}<NumberFlow
								value={Number(height(viewDisplayedLevel))}
								format={{ minimumFractionDigits: 1, maximumFractionDigits: 1 }}
							/>{/if}<span class="ml-1 text-sm text-muted-foreground">{symbol}</span>
					</p>
				</div>
				<div class="text-right text-xs text-muted-foreground">
					<p>
						{viewHovered
							? 'Selected time'
							: viewTide.next
								? viewTide.next.type === 'H'
									? 'Rising toward high tide'
									: 'Falling toward low tide'
								: 'Tide outlook'}
					</p>
					<p class="mt-1 tabular-nums" data-slot="tide-time">
						<span class="sr-only">{time(viewDisplayedTime)}</span><span aria-hidden="true"
							>{#each viewTimeParts as part}{#if part.type === 'hour' || part.type === 'minute'}<NumberFlow
										value={Number(part.value)}
										format={{
											minimumIntegerDigits: part.type === 'minute' ? 2 : 1,
											useGrouping: false
										}}
									/>{:else}{part.value}{/if}{/each}</span
						>
					</p>
				</div>
			</div>
			{#if viewChartData.length > 1}
				<ChartUI.Container
					config={{ height: { label: 'Tide level', color: 'var(--chart-1)' } }}
					class={`aspect-auto w-full ${size === 'sm' ? 'h-20' : size === 'lg' ? 'h-36' : 'h-28'}`}
					role="img"
					aria-label="Tide prediction curve with predicted water level marker"
				>
					<Chart
						bind:context={
							() => (day ? dayChartContext : chartContext),
							(value) => {
								if (day) dayChartContext = value;
								else chartContext = value;
							}
						}
						data={viewChartData}
						x="time"
						y="height"
						yDomain={viewDomain}
						series={[{ key: 'height', label: 'Tide level', color: 'var(--chart-1)' }]}
						tooltipContext={{ mode: 'bisect-x' }}
						padding={{ top: 8, right: 8, bottom: 4, left: 8 }}
					>
						{#snippet children({ context })}
							<Svg>
								<Area
									curve={curveMonotoneX}
									fill="color-mix(in oklab, var(--chart-1) 12%, transparent)"
									line={{
										stroke: 'var(--chart-1, var(--primary))',
										strokeWidth: 2,
										fill: 'none',
										opacity: 1
									}}
									motion={{ type: 'tween', duration: 0 }}
								/>
								{#if viewIndicatorLevel !== null && viewIndicatorTime >= viewChartData[0].time && viewIndicatorTime <= viewChartData[viewChartData.length - 1].time}
									<line
										x1={context.xScale(viewIndicatorTime)}
										x2={context.xScale(viewIndicatorTime)}
										y1={0}
										y2={context.height}
										stroke="var(--muted-foreground)"
										stroke-dasharray="3 4"
									/>
									<circle
										data-slot="current-tide-marker"
										cx={context.xScale(viewIndicatorTime)}
										cy={context.yScale(viewIndicatorLevel)}
										r={4.5}
										fill="var(--chart-1, var(--primary))"
										stroke="var(--card)"
										stroke-width="2"
									/>
								{/if}
							</Svg>
						{/snippet}
					</Chart>
				</ChartUI.Container>
				<div class="-mt-2 flex justify-between text-[10px] text-muted-foreground">
					<span>{time(viewChartData[0].time)}</span><span
						>MLLW · {viewTide.points.length ? 'predicted curve' : 'extrema only'}</span
					><span>{time(viewChartData.at(-1)!.time)}</span>
				</div>
			{/if}
			<div class="grid grid-cols-2 gap-3 border-t pt-3">
				{#each [{ label: 'Previous', event: viewTide.previous }, { label: 'Next', event: viewTide.next }] as entry}
					<div>
						<p class="text-xs text-muted-foreground">
							{entry.label}
							{entry.event ? (entry.event.type === 'H' ? 'high tide' : 'low tide') : 'tide'}
						</p>
						<p class="mt-1 text-sm font-medium tabular-nums">
							{entry.event ? time(entry.event.time) : 'Unavailable'}
						</p>
						{#if entry.event}<p class="mt-1 text-xs text-muted-foreground">
								{height(Number(entry.event.height))}
								{symbol}
							</p>{/if}
					</div>
				{/each}
			</div>
			{#if type !== 'simple'}
				<div class="divide-y border-t">
					{#each viewTide.events
						.filter((p) => tideTimestamp(p.time) > viewNow)
						.slice(0, type === 'detailed' ? 6 : density === 'compact' ? 2 : 4) as event}<div
							class={`flex justify-between gap-2 text-xs ${density === 'compact' ? 'py-2' : 'py-3'}`}
						>
							{#if interactive && size !== 'lg' && !day}<button
									type="button"
									class="min-h-8 text-left underline-offset-4 hover:underline focus-visible:outline-2 focus-visible:outline-ring"
									aria-label={`View tide details for ${dateTime(event)}`}
									onclick={(e) =>
										openDay(new Date(tideTimestamp(event.time)).toISOString(), e.currentTarget)}
									>{event.type === 'H' ? 'High tide' : 'Low tide'}</button
								>{:else}<span>{event.type === 'H' ? 'High tide' : 'Low tide'}</span>{/if}<span
								class="ml-auto text-muted-foreground">{dateTime(event)}</span
							><span class="tabular-nums">{height(Number(event.height))} {symbol}</span>
						</div>{/each}
				</div>
			{/if}
		{:else}<p role="status" class="py-8 text-center text-sm text-muted-foreground">
				No tide predictions available.
			</p>{/if}
		{#if !day && sourceLabel}<p class="text-[10px] text-muted-foreground">{sourceLabel}</p>{/if}
	</Card.Content>
{/snippet}

<Card.Root
	style="container-type: inline-size"
	size={size === 'sm' ? 'sm' : 'default'}
	data-density={density}
	data-card-size={size}
	class={`relative isolate min-w-0 overflow-hidden ${className}`}
>
	<ForecastScreens
		interactive={interactive && size !== 'lg'}
		{days}
		title="Tide"
		{density}
		{sourceLabel}
		{iconType}
		showWeek
		actionLabel="Upcoming tides"
	>
		{#snippet summary(availableHeight)}
			<div class="divide-y" data-slot="upcoming-tides">
				{#each tide.events
					.filter((event) => tideTimestamp(event.time) >= now)
					.slice(0, Math.max(1, Math.floor(availableHeight / 32))) as event}
					<div class="flex h-8 items-center justify-between gap-2 text-xs">
						<span class="flex shrink-0 items-center gap-1"
							><ForecastIcon
								name={event.type === 'H' ? 'arrowUp' : 'arrowDown'}
								iconSet={iconType}
								class="size-3"
							/>{event.type === 'H' ? 'High' : 'Low'}</span
						>
						<span class="truncate text-muted-foreground">{time(event.time)}</span>
						<span class="shrink-0 tabular-nums">{height(Number(event.height))} {symbol}</span>
					</div>
				{/each}
			</div>
		{/snippet}
		{#snippet children(openDay, action, visible)}
			{@render cardView(undefined, action, openDay)}
		{/snippet}
		{#snippet detail(day, action)}
			{@render cardView(day, action, () => {})}
		{/snippet}
	</ForecastScreens>
</Card.Root>
